import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weatherly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID"></Script>
      <Script id="google-analytics">
        {
          `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-W3T3LYY278');
          `
        }
      </Script>
    </head>
    <body className={inter.className}>{children}</body>
  </html>
  );
}
